title: Ha Ha Yes
author: Rey M.
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is just to test out coding experience.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
